export const SOLANA_PROGRAM_IDS = {
  PUMP_FUN: '6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P',
  PUMP_SWAP: 'PSwapMdSai8tjrEXcxFeQth87xC4rRsa4VA5mhGhXkP',
  JUPITER: 'JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4',
  RAYDIUM_AMM: '675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8',
  RAYDIUM_CLMM: 'CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK',
  ORCA_WHIRLPOOL: 'whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc',
  TOKEN_PROGRAM: 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  ASSOCIATED_TOKEN_PROGRAM: 'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL',
  SYSTEM_PROGRAM: '11111111111111111111111111111111'
};

export const MONITORED_TRADING_PROGRAMS = [
  SOLANA_PROGRAM_IDS.PUMP_FUN,
  SOLANA_PROGRAM_IDS.PUMP_SWAP,
  SOLANA_PROGRAM_IDS.JUPITER,
  SOLANA_PROGRAM_IDS.RAYDIUM_AMM,
  SOLANA_PROGRAM_IDS.RAYDIUM_CLMM,
  SOLANA_PROGRAM_IDS.ORCA_WHIRLPOOL
];

export const PROGRAM_LABELS = {
  [SOLANA_PROGRAM_IDS.PUMP_FUN]: 'Pump.fun',
  [SOLANA_PROGRAM_IDS.PUMP_SWAP]: 'PumpSwap',
  [SOLANA_PROGRAM_IDS.JUPITER]: 'Jupiter',
  [SOLANA_PROGRAM_IDS.RAYDIUM_AMM]: 'Raydium AMM',
  [SOLANA_PROGRAM_IDS.RAYDIUM_CLMM]: 'Raydium CLMM',
  [SOLANA_PROGRAM_IDS.ORCA_WHIRLPOOL]: 'Orca Whirlpool'
};

export function getProgramLabel(programId) {
  return PROGRAM_LABELS[programId] || programId;
}

export function isMonitoredTradingProgram(programId) {
  return MONITORED_TRADING_PROGRAMS.includes(String(programId || ''));
}
