[features]
seeds = false
skip-lint = false

[programs.localnet]
saintrocky_escrow = "CT1KzU4EtRSHyjTmFtemKcJGXcTQWc6K6He1PfpZuqsU"

[programs.devnet]
saintrocky_escrow = "CT1KzU4EtRSHyjTmFtemKcJGXcTQWc6K6He1PfpZuqsU"

[workspace]
members = ["escrow"]

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
